accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from accounts.views import RecipeListView, RecipeDetailView, MyProfileView, RecipeJustDetailView, MenuListView, MenuDetailView, MenuJustDetailView

app_name ='accounts'

urlpatterns=[
    path('signup/', views.register, name='signup'),
    path('user_login/', views.user_login, name='user_login'),
    path('edit_user_profile/', views.edit_user_profile, name='edit_user_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('profile_page/', MyProfileView.as_view(), name='profile_page'),
    path('search_page/', views.search_list, name='search_page'),
    path('create_recipe/', views.create_recipe, name='create_recipe'),
    path('create_menu/', views.create_menu, name='create_menu'),
    path('list_recipes/<int:user_profile_id>', RecipeListView.as_view(), name='list_recipes'),
    path('list_menus/<int:user_profile_id>', MenuListView.as_view(), name='list_menus'),
    path('myrecipe_details/<int:user_profile_id>/<int:pk>', RecipeDetailView.as_view(), name='my_recipe_details'),
    path('recipe_details/<int:user_profile_id>/<int:pk>', RecipeJustDetailView.as_view(), name='recipe_details'),
    path('mymenu_details/<int:user_profile_id>/<int:pk>', MenuDetailView.as_view(), name='my_menu_details'),
    path('menu_details/<int:user_profile_id>/<int:pk>', MenuJustDetailView.as_view(), name='menu_details'),
    path('add_comment/<int:user_id>/<int:recipe_id>', views.add_comment, name='add_comment'),
    path('like/<int:user_id>/<int:recipe_id>', views.like, name='like'),
    path('detail/<int:user_profile_id>/', views.user_detail, name='detail'),
]

hungryForRecipe/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name="home"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
#from django.contrib.gis.db import models as geoModels
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type=models.CharField(max_length=50,default="")
    #consumer
    birthday=models.CharField(max_length=50,default="")
    #provider
    provider_name=models.CharField(max_length=50,default="")
    #location = geoModels.PointField()
    address=models.CharField(max_length=50,default="")
    phone_number=models.CharField(max_length=50,default="")
    def __str__(self):
        return self.user.username

class Recipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50,default="")
    description=models.CharField(max_length=50,default="")
    instructions = models.TextField(max_length=1500,default="")
    duration = models.CharField(max_length=50,default="")
    level=models.CharField(max_length=10,default="")
    ingredients = models.TextField(max_length=50000,default="")
    nutrients = models.TextField(max_length=50000,default="")
    #ingredients = models.OneToOneField('Ingredient', on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class Comment(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description=models.CharField(max_length=1000,default="")
    def __str__(self):
        return self.description

class Like(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    user_profile = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE)
    description=models.CharField(max_length=50,default="")
    def __str__(self):
        return self.description

class Menu(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, default="")
    def __str__(self):
        return self.title


class Meal(models.Model):
    recipe_id = models.IntegerField(default=0)
    title = models.CharField(max_length=50,default="")
    menu_title=models.CharField(max_length=50,default="")
    menu=models.ForeignKey(Menu, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class LikeForMenu(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description=models.CharField(max_length=50,default="")
    def __str__(self):
        return self.description

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo,Recipe
from django.contrib.auth.forms import PasswordChangeForm

LEVEL_CHOICES= [
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
    ]

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','first_name','last_name','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('user_type','birthday','provider_name','address','phone_number')


class EditProfileForm(forms.ModelForm):
    #password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','first_name','last_name','email')

class CreateRecipeForm(forms.ModelForm):
    class Meta():
        model = Recipe
        fields = ('title','description','instructions','duration')

class PasswordChangeCustomForm(PasswordChangeForm):
    def __init__(self, user, *args, **kwargs):
        super(PasswordChangeCustomForm, self).__init__(user,*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class UpdateRecipeForm(forms.ModelForm):
    class Meta():
        model = Recipe
        fields = ('title','description','instructions','duration')

accounts/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm, EditProfileForm, CreateRecipeForm, PasswordChangeCustomForm, \
    UpdateRecipeForm
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import Recipe, UserProfileInfo, Comment, Like, Menu, Meal
from django.contrib.auth.models import User
from django.db.models import Q
from django.views.generic import (ListView, DetailView)


@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse_lazy("login"))


def register(request):
    registered = False
    errorMessage = ""
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            password = request.POST.get('password')
            user.set_password(password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
            errorMessage = "Registered"
        else:
            print(user_form.errors, profile_form.errors)
            errorMessage = "Not registered"
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'accounts/signup.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered,
                   'error_Message': errorMessage
                   })


def user_login(request):
    loginFailed = False
    errorMessage = ""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse_lazy("home"))
            else:
                loginFailed = True
                errorMessage = "Your account is not active"
                # return HttpResponse("Your account is not active.")
        else:
            loginFailed = True
            errorMessage = "Invalid login,check your username and password!"
    return render(request, 'accounts/login.html', {'loginFailed': loginFailed,
                                                   'errorMessage': errorMessage
                                                   })


def edit_user_profile(request):
    isUpdated = False
    user = request.user
    userProfile = UserProfileInfo.objects.get(user=user)
    if request.method == 'POST':
        edit_profile_form = EditProfileForm(data=request.POST, instance=request.user)
        if edit_profile_form.is_valid():
            edit_profile_form.save()
            isUpdated = True

        else:
            print(edit_profile_form.errors)
        '''
        user.username=request.POST['username']
        user.first_name=request.POST['first_name']
        user.last_name=request.POST['last_name']
        user.email=request.POST['email']
        user.save()
        '''

    else:
        edit_profile_form = EditProfileForm(instance=request.user)
        # edit_profile_form.email=request.user

    return render(request, 'accounts/editProfile.html',
                  {'edit_profile_form': edit_profile_form,
                   'user': user,
                   'userProfile': userProfile,
                   'isUpdated': isUpdated
                   })


def change_password(request):
    isChanged = False
    if request.method == 'POST':
        change_password_form = PasswordChangeCustomForm(data=request.POST, user=request.user)
        if change_password_form.is_valid():
            change_password_form.save()
            isChanged = True
        else:
            print(change_password_form.errors)
    else:
        change_password_form = PasswordChangeCustomForm(user=request.user)
        # edit_profile_form.email=request.user

    return render(request, 'accounts/changePassword.html',
                  {'change_password_form': change_password_form,
                   'isChanged': isChanged
                   })


def create_recipe(request):
    title = ""
    description = ""
    instructions = ""
    duration = ""
    level = ""
    ingredients = ""
    error_Message = ""
    isOk = ""
    user = request.user
    isConsumer=False
    if request.method == 'POST':
        user_form = CreateRecipeForm(request.POST)
        if user_form.is_valid():
            user = request.user
            userProfile = UserProfileInfo.objects.get(user=user)
            if userProfile.user_type=="consumer":
                isConsumer=True
            title = user_form.cleaned_data.get('title')
            description = user_form.cleaned_data.get('description')
            instructions = user_form.cleaned_data.get('instructions')
            duration = user_form.cleaned_data.get('duration')
            level = request.POST.get('level')
            ingredients = request.POST.get('hiddenIngList')
            nutrients = request.POST.get('nutrientsTotal')

            if ingredients is None:
                error_Message = "First select ingredients!"
                isOk = "First select ingredients!"
            else:
                Recipe.objects.create(user=user, title=title, description=description, instructions=instructions,
                                      duration=duration, level=level, ingredients=ingredients, nutrients=nutrients)
                isOk = "saved with " + ingredients
            recipes = Recipe.objects.filter(user=user)
            return render(request, 'accounts/list_recipes.html',
                          {'recipes': recipes,
                           'errorMessage': error_Message,
                           'userProfile': userProfile,
                           'isConsumer':isConsumer
                           })
            # return HttpResponseRedirect(reverse_lazy("accounts:list_recipes",kwargs={'pk': user.userprofileinfo.id}))
    else:
        user_form = CreateRecipeForm()
        if user_form.is_valid():
            Recipe.objects.create(user=user, title=title, description=description, instructions=instructions,
                                  duration=duration, level=level, ingredients=ingredients)

    return render(request, 'accounts/create_recipe.html',
                  {'user_form': user_form,
                   'title': title,
                   'description': description,
                   'instructions': instructions,
                   'duration': duration,
                   'level': level,
                   'ingredients': ingredients,
                   'error_Message': error_Message,
                   'isOk': isOk,
                   })


class RecipeListView(ListView):
    def get(self, request, **kwargs):
        errorMessage = ""
        isConsumer=False
        if request.method == "GET":
            user_profile_id = self.kwargs.get('user_profile_id')
            userProfile = UserProfileInfo.objects.get(id=user_profile_id)
            if userProfile.user_type=="consumer":
                isConsumer=True
            recipes = Recipe.objects.filter(user=userProfile.user)
            if recipes is None:
                errorMessage = "No recipe is created!"
            return render(request, 'accounts/list_recipes.html',
                          {'recipes': recipes,
                           'errorMessage': errorMessage,
                           'userProfile': userProfile,
                           'isConsumer': isConsumer
                           })


class RecipeDetailView(DetailView):
    def get(self, request, **kwargs):
        errorMessage = ""
        if request.method == "GET":
            recipe_id = self.kwargs.get('pk')
            recipe = Recipe.objects.get(pk=recipe_id)
            if recipe is None:
                errorMessage = "No recipe is created!"
        return render(request, 'accounts/recipe_details.html',
                      {'recipe': recipe,
                       'errorMessage': errorMessage,
                       })

    def post(self, request, **kwargs):
        errorMessage = ""
        user_form = UpdateRecipeForm(request.POST)
        if request.method == "POST":
            recipe_id = self.kwargs.get('pk')
            recipe = Recipe.objects.get(pk=recipe_id)
            if user_form.is_valid():
                recipe.title = user_form.cleaned_data.get('title')
                recipe.description = user_form.cleaned_data.get('description')
                recipe.instructions = user_form.cleaned_data.get('instructions')
                recipe.duration = user_form.cleaned_data.get('duration')
                recipe.level = request.POST.get('level')
                recipe.ingredients = request.POST.get('hiddenIngList')
                recipe.nutrients = request.POST.get('nutrientsTotal')
                if recipe.ingredients is None:
                    errorMessage = "First select ingredients!"
                else:
                    if request.POST.get("Update"):
                        recipe.save()
                    # else:
                    #    recipe.delete()
                    #    return redirect(reverse('accounts:list_recipes'))
            return render(request, 'accounts/recipe_details.html',
                          {'recipe': recipe,
                           'errorMessage': errorMessage,
                           })


class RecipeJustDetailView(DetailView):
    def get(self, request, **kwargs):
        errorMessage = ""
        if request.method == "GET":
            id = self.kwargs.get('pk')

accounts/templates/accounts/add_comment.html
{% extends "base.html"%}
{% load bootstrap3%}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <form method="POST">
                <h3>Add Comment</h3>
                {% csrf_token %}
                <div class="form-group">
                    <div class="input-group mb-3">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"  id="inputGroup-sizing-default">Comment</span>
                            </div>
                            <textarea rows="8" cols="80"  maxlength="1000" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" id="comment" name="comment" required> </textarea>
                        </div>
                        <div class="form-group row text-right">
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                <input type="submit" class="btn btn-outline-primary" value="Save">
                            </div>
                        </div>
                    </div>
                </div>
        </div>
{% endblock %}

accounts/templates/accounts/changePassword.html
{% extends "base.html"%}
{% load bootstrap3%}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <form method="POST">
                {{ change_password_form.as_p }}
                {% csrf_token %}
                <div class="form-group row text-right">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <input type="submit" class="btn btn-outline-primary" value="Save">
                    </div>
                </div>
            </form>
            {%if isChanged %}
                <h3>Your password is changed!</h3>
            {%endif%}
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/create_menu.html
{% extends "base.html"%}
{% load bootstrap3%}
{% block content %}
    <div class="container">
    <div class="jumbotron">
        <form method="POST">
            {% csrf_token %}
            <h2>Create Menu</h2>
            <div class="form-group">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Title</span>
                    </div>
                    <input type="text" maxlength="50" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" id="title" name="title" required>
                </div>
                <div class="form-group row text-right">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <input type="submit" class="btn btn-outline-primary" value="Save" id="Save" name="Save">
                    </div>
                </div>
            </div>
    </div>
{% endblock %}

accounts/templates/accounts/editProfile.html
{% extends "base.html"%}
{% load bootstrap3%}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <form method="POST">
                {% if isUpdated %}
                    <h3>Your profile info is updated!</h3>
                {% else %}
                    <h3>Update</h3>
                    {% csrf_token %}
                    <div class="form-group">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">UserName</span>
                        </div>
                        <input type="text"  value="{{ user.username }}" class="form-control" aria-label="Default" required="required" aria-describedby="inputGroup-sizing-default" id="username" name="username">
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">First Name</span>
                        </div>
                        <input type="text"  value="{{ user.first_name }}" class="form-control" aria-label="Default" required="required" aria-describedby="inputGroup-sizing-default" id="first_name" name="first_name">
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">Last Name</span>
                        </div>
                        <input type="text"  value="{{ user.last_name }}" class="form-control" aria-label="Default" required="required" aria-describedby="inputGroup-sizing-default" id="last_name" name="last_name">
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">Email</span>
                        </div>
                        <input type="email"  value="{{ user.email }}" class="form-control" aria-label="Default" required="required" aria-describedby="inputGroup-sizing-default" id="email" name="email">
                    </div>
                    <div class="form-group row text-right">
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <input type="submit" class="btn btn-outline-primary" value="Save">
                        </div>
                    </div>
                {% endif %}
                </div>
        </div>
{% endblock %}

accounts/templates/accounts/list_recipes.html
{% extends "base.html"%}
{% load bootstrap3%}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <form method='POST'>
                {% if isConsumer  %}
                    <h3>{{userProfile.user.username}}'s Recipes</h3>
                {% else %}
                    <h3>{{userProfile.provider_name}}'s Recipes</h3>
                {% endif %}
                <div class="form-group">
                    {% for recipe in recipes %}
                        <div>
                            {% if request.user ==  userProfile.user  %}
                                <a href="{% url 'accounts:my_recipe_details'  user_profile_id=userProfile.id pk=recipe.id %}">{{ recipe.title }}</a>
                            {% else %}
                                <a href="{% url 'accounts:recipe_details'  user_profile_id=userProfile.id pk=recipe.id %}">{{ recipe.title }}</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    {% if request.user ==  userProfile.user  %}
                        <a href="{% url 'accounts:create_recipe' %}">Create Recipe</a>
                    {% endif %}
                </div>
                {{errorMessage}}
            </form>
        </div>
    </div>

    <script>




    </script>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html"%}
{% load bootstrap3%}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h3>Log In</h3>
            <form method="post" action="{% url 'accounts:user_login' %}">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">UserName</span>
                    </div>
                    <input type="text" class="form-control" placeholder="Username" aria-label="Default" required="required" aria-describedby="inputGroup-sizing-default" id="username" name="username">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Password</span>
                    </div>
                    <input type="password" class="form-control" placeholder="Password" aria-label="Default" required="required" aria-describedby="inputGroup-sizing-default" id="password" name="password">
                </div>
                <div class="form-group row text-right">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <input type="submit" class="btn btn-outline-primary" value="Login">
                    </div>
                </div>
            </form>
            {% if not isLoggedIn %}
                <h6>{{errorMessage}}</h6>
            {% endif %}
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html"%}
{% load bootstrap3%}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            {% if userProfile.user_type == "consumer" %}
                <h3>{{user.username}}'s Profile</h3>
            {% else %}
                <h3>{{userProfile.provider_name}}'s Profile</h3>
            {% endif %}
            {% if userProfile.user_type == "consumer" %}
                <p>First name: {{user.first_name}}</p>
                <p>Last name: {{user.last_name}}</p>
                <p>Email: {{user.email}}</p>
                <p id>Birthday: {{userProfile.birthday}}</p>
                <div>
                    <a href="{% url 'accounts:list_recipes' userProfile.id %}">{{user.username}}'s Recipes</a>
                </div>
                <div>
                    <a href="{% url 'accounts:list_menus' userProfile.id %}">{{user.username}}'s Menus</a>
                </div>
            {% else %}
                <p>Provider Name: {{userProfile.provider_name}}</p>
                <p>Address: {{userProfile.address}}</p>
                <p>Phone Number: {{userProfile.phone_number}}</p>
                <div>
                    <a href="{% url 'accounts:list_recipes' userProfile.id %}">{{userProfile.provider_name}}'s Recipes</a>
                </div>
                <div>
                    <a href="{% url 'accounts:list_menus' userProfile.id %}">{{userProfile.provider_name}}'s Menus</a>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/search.html
{% extends "base.html"%}
{% load bootstrap3%}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <form method='GET'>
                <h3>Search</h3>
                {% csrf_token %}
                <div class="form-group">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">Type</span>
                        </div>
                        <select class="form-control" id="type" name="type" onchange="onChangeType(this.value)" required>
                            {%if displayUser  %}
                                <option value="user">User</option>
                                <option value="recipe">Recipe</option>
                            {%elif displayRecipe %}
                                <option value="recipe">Recipe</option>
                                <option value="user">User</option>
                            {%else%}
                                <option value="user">User</option>
                                <option value="recipe">Recipe</option>
                            {% endif %}
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">Search term</span>
                            <input type="text" maxlength="50" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" id="term" placeholder="Search" name='search' value="{{search_term}}">
                            <button id="search" class="btn btn-outline-primary">Search</button>
                        </div>
                    </div>
                    {%if displayUser  %}
                        <h3 id="user_header">Users</h3>
                        <ul class="list-group" id="user_list">
                            {% for userProfile in userProfiles %}
                                <li class="list-group-item">
                                    {% if userProfile.user_type == "consumer"  %}
                                        <a href="{% url 'accounts:detail' userProfile.id %}">{{ userProfile }}</a>
                                    {% else %}
                                        <a href="{% url 'accounts:detail' userProfile.id %}">{{ userProfile.provider_name }}</a>
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    {%elif displayRecipe %}
                        <h3 id="recipe_header">Recipes</h3>
                        <ul class="list-group" id="recipe_list">
                            {% for recipe in recipes %}
                                <div>
                                    {% if request.user ==  recipe.user  %}
                                        <a href="{% url 'accounts:my_recipe_details'  user_profile_id=request.user.id pk=recipe.id %}">{{ recipe.title }}</a>
                                    {% else %}
                                        <a href="{% url 'accounts:recipe_details'  user_profile_id=recipe.user.id pk=recipe.id %}">{{ recipe.title }}</a>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            $(function(e){
                onChangeType();
            })
        })
        function onChangeType(){
            if($("#type").val()=="user"){
                $("#term").empty();
                recipe_head=document.getElementById("recipe_header");
                recipe_list=document.getElementById("recipe_list");
                if(typeof(recipe_head) != 'undefined' && recipe_head != null)
                    recipe_head.innerHTML="Users";
                if(typeof(recipe_list) != 'undefined' && recipe_list != null)
                    $("#recipe_list").empty();

            }
            else {
                $("#term").empty();
                user_head=document.getElementById("user_header");
                user_list=document.getElementById("user_list");
                if(typeof(user_head) != 'undefined' && user_head != null)
                    user_head.innerHTML="Recipes";
                if(typeof(user_list) != 'undefined' && user_list != null)
                    $("#user_list").empty();
            }
        }
    </script>
{% endblock %}