accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from accounts.views import RecipeListView, RecipeDetailView, MyProfileView, RecipeJustDetailView, MenuListView, MenuDetailView, MenuJustDetailView

app_name ='accounts'

urlpatterns=[
    path('signup/', views.register, name='signup'),
    path('user_login/', views.user_login, name='user_login'),
    path('edit_user_profile/', views.edit_user_profile, name='edit_user_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('profile_page/', MyProfileView.as_view(), name='profile_page'),
    path('search_page/', views.search_list, name='search_page'),
    path('create_recipe/', views.create_recipe, name='create_recipe'),
    path('create_menu/', views.create_menu, name='create_menu'),
    path('list_recipes/<int:user_profile_id>', RecipeListView.as_view(), name='list_recipes'),
    path('list_menus/<int:user_profile_id>', MenuListView.as_view(), name='list_menus'),
    path('myrecipe_details/<int:user_profile_id>/<int:pk>', RecipeDetailView.as_view(), name='my_recipe_details'),
    path('recipe_details/<int:user_profile_id>/<int:pk>', RecipeJustDetailView.as_view(), name='recipe_details'),
    path('mymenu_details/<int:user_profile_id>/<int:pk>', MenuDetailView.as_view(), name='my_menu_details'),
    path('menu_details/<int:user_profile_id>/<int:pk>', MenuJustDetailView.as_view(), name='menu_details'),
    path('add_comment/<int:user_id>/<int:recipe_id>', views.add_comment, name='add_comment'),
    path('like/<int:user_id>/<int:recipe_id>', views.like, name='like'),
    path('detail/<int:user_profile_id>/', views.user_detail, name='detail'),
]

hungryForRecipe/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name="home"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hungry For Recipe</title>
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">HungryForRecipe</a>
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'accounts:profile_page' %}" class="btn btn-simple">Profile</a>
          <a class="nav-item nav-link" href="{% url 'accounts:search_page' %}" class="btn btn-simple">Search</a>

          {% endif %}
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <div class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
               <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                 <a class="dropdown-item" href="{% url 'accounts:edit_user_profile' %}">Update account info</a>
                 <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change password</a>
               </div>
            </div>
            <a class="nav-item nav-link" href="{% url 'logout' %}" class="btn btn-simple">Log out</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:user_login' %}" class="btn btn-simple">Log in</a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>

  </body>
</html>

templates/index.html
{% extends "base.html"%}
{% block content %}
<div class="container">
  <div class="jumbotron">
  {% if user.is_authenticated %}
    <h3>Welcome to HungryForRecipe, {{loggedInUser}}!</h3>
  {% else %}
    <h3>Welcome to HungryForRecipe!</h3>
  {% endif %}
  </div>
</div>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h3>Thanks for visiting! Come back soon!</h3>
</div>
</div>
{% endblock %}